# Generated by Django 4.2 on 2023-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('option1', 'Meal Swipe Requests'), ('option2', 'Points Requests'), ('option3', 'Club Announcements'), ('option4', 'Selfless Swipes')], default='Meal Swipe Requests', max_length=20),
            preserve_default=False,
        ),
    ]
